-- ============================================================
-- iTradeJournal — Mentor Review Mode schema
-- Run this in the Supabase SQL editor (once) to enable
-- shareable read-only review links + mentor comments.
-- Also powers the in-app Notification Center (mentor feedback).
-- Safe to re-run: policies are dropped before being recreated.
-- ============================================================

create table if not exists public.review_sessions (
  token text primary key,
  trade_ids jsonb not null default '[]'::jsonb,
  trades_snapshot jsonb not null default '[]'::jsonb,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.review_comments (
  id bigint generated by default as identity primary key,
  session_token text not null references public.review_sessions(token) on delete cascade,
  trade_id text,
  author text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists review_comments_session_idx
  on public.review_comments (session_token, created_at);

alter table public.review_sessions enable row level security;
alter table public.review_comments enable row level security;

-- Anyone with a token can read a review session.
drop policy if exists "review_sessions_public_read" on public.review_sessions;
create policy "review_sessions_public_read"
  on public.review_sessions for select
  using (true);

-- Signed-in traders create sessions.
drop policy if exists "review_sessions_auth_insert" on public.review_sessions;
create policy "review_sessions_auth_insert"
  on public.review_sessions for insert
  to authenticated
  with check (true);

-- Anyone with the link can read the feedback.
drop policy if exists "review_comments_public_read" on public.review_comments;
create policy "review_comments_public_read"
  on public.review_comments for select
  using (true);

-- Anyone with the link (mentors without accounts) can post feedback.
drop policy if exists "review_comments_public_insert" on public.review_comments;
create policy "review_comments_public_insert"
  on public.review_comments for insert
  with check (true);
